const socket = require("socket.io")
const {saveMessageToDB} = require("./controller/ChatController")

socketServer = (server)=>{
    const io = socket(server,{
        cors:{
            origin:"http://localhost:3000",
            methods:["GET","POST"]
        }
    })

    io.on("connection", (socket)=>{    // socket is a object automaticaly generated by socket.io for each client
        // console.log("socket", socket);
         
        console.log("User connected", socket.id);

        socket.on("sendMessage", async (messageData)=>{       // listen for sendMessage from frontend
            console.log("message sent");
            console.log("from client:", messageData);
            
            const savedMessage = await saveMessageToDB(messageData)
            console.log("savedMeassge",savedMessage);
            
            io.emit("receiveMessage", savedMessage)        // broadcast the receiving message to client and front frontend will listen the receiveMessage
        })
       
        socket.on("disconnect",()=>{
            console.log("User disconnected", socket.id);
        })
        
    })
}

module.exports = socketServer

